server:
  port: ${PORT:${SERVER_PORT:0}} # SI NO HAY UNO DEFINIDO AGARRA UNO ALETORIO LIBRE (0)
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

spring:
  zipkin:
    base-url: http://localhost:9411
    enabled: true

management:
  tracing:
    sampling:
      probability: 1.0
