spring:
  application:
    name: gateway-service
  config:
    import: optional:configserver:http://localhost:8081
  security:
    oauth2:
      client:
        registration:
          tutorial-client:
            provider: keycloak
            client-id: tutorial-client
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/tutorial-client"
            scope:
              - openid
              - profile
              - email
        provider:
          keycloak:
            issuer-uri: http://localhost:8180/realms/tutorial


logging:
  level:
    org.springframework.security: DEBUG