spring:
  application:
    name: car-service
  config:
    import: optional:configserver:http://localhost:8081
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/tutorial
logging:
  level:
    org.springframework.cloud.openfeign: DEBUG
    brave: DEBUG