server:
  port: 8081

spring:
  cloud:
    config:
      server:
        git:
          default-label: master
          uri: https://github.com/mishelrodri/test-micro
          search-paths: config-data
#          username: mishelrodri
#          password: token basic
  application:
    name: config-service